# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "radiant-sitemap_search-extension"
  s.version = "1.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew vonderLuft", "Sean Cribbs"]
  s.date = "2013-01-30"
  s.description = "Adds search feature for pages, snippets, layouts, et al."
  s.email = "avonderluft@avlux.net"
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "HELP.textile",
    "README.textile",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/search_controller.rb",
    "app/helpers/admin/search_helper.rb",
    "app/views/admin/pages/index.html.haml",
    "app/views/admin/pages/page_list_view.html.haml",
    "app/views/admin/search/_banner.html.haml",
    "app/views/admin/search/_banner_index_bottom.html.haml",
    "app/views/admin/search/_layout.html.haml",
    "app/views/admin/search/_layout_index_bottom.html.haml",
    "app/views/admin/search/_results_nav.html.haml",
    "app/views/admin/search/_search_action.html.haml",
    "app/views/admin/search/_snippet.html.haml",
    "app/views/admin/search/_snippet_index_bottom.html.haml",
    "app/views/admin/search/_template.html.haml",
    "app/views/admin/search/_template_index_bottom.html.haml",
    "app/views/admin/search/index.html.haml",
    "config/locales/en.yml",
    "config/routes.rb",
    "lib/sitemap_search/model.rb",
    "lib/tasks/sitemap_search_extension_tasks.rake",
    "radiant-sitemap_search-extension.gemspec",
    "sitemap_search_extension.rb",
    "spec/controllers/search_controller_spec.rb",
    "spec/models/page_extensions_spec.rb",
    "spec/models/snippet_extensions_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "https://github.com/avonderluft/radiant-sitemap_search-extension"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Sitemap Search Extension for Radiant CMS"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<radiant>, [">= 1.0.0.rc2"])
    else
      s.add_dependency(%q<radiant>, [">= 1.0.0.rc2"])
    end
  else
    s.add_dependency(%q<radiant>, [">= 1.0.0.rc2"])
  end
end

